apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend
- frontend
- base
commonLabels:
  app: todoapp
images:
- name: todoapp-backend
  newName: europe-west9-docker.pkg.dev/projet-1-496616/todoapp-repository/todoapp-backend
  newTag: v1.0.10
- name: todoapp-frontend
  newName: europe-west9-docker.pkg.dev/projet-1-496616/todoapp-repository/todoapp-frontend
  newTag: v1.0.1
